### ISSUE TITLE
Jira Server integration broken

### ISSUE THREAD

**Issue by ann-mwangi** [OctopusDeploy/JiraIntegration#45]
We’ve recently upgraded to the latest Octopus version, up from 2020.5 and found that the integration with Jira Server is broken for us in the new release.

Issue raised here: https://help.octopus.com/t/jira-server-integration-broken/27007

**Comment by hnrkndrssn** [comment]
This issue has been fixed in Octopus `2021.2` and `2021.3` as part of #56
