### ISSUE TITLE
Jira issue search failing to deserialize response

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/JiraIntegration#56]
After being upgraded to Octopus `2021.2.7428` a number of customers are reporting that they are seeing errors similar to the below:
```
Error converting value "blablabal" to type 'Octopus.Server.Extensibility.JiraIntegration.Integration.JiraDoc'. Path 'issues[1].fields.comment.comments[0].body', line 1, position 2381. Could not cast or convert from System.String to Octopus.Server.Extensibility.JiraIntegration.Integration.JiraDoc.
```

**Comment by millerjn21** [comment]
Two more reports:
https://help.octopus.com/t/no-issue-links-or-jira-story-updates/27134/7
https://help.octopus.com/t/jira-issue-tracker-setup-issues/27102/16

**Comment by raymens** [comment]
Great to see it's fixed, thanks!

However In what version should this be fixed? As we're still facing this issue in 2021.2.7462 (coming from 2021.2.7428).

**Comment by Antoni-Eng** [comment]
I still have the issue in 2021.7462 too.

**Comment by millerjn21** [comment]
Hey all, sorry about that. I dug into the commits and see that the earliest release it will be in is 2021.2.7523. This should hopefully be out in the next week or so.

Please let us know if you have any other questions or concerns.

**Comment by matt-richardson** [comment]
Release note: Fixed issue retrieving Jira issues that have comments
