### ISSUE TITLE
Include Tenant name in Jira Environment DisplayName

### ISSUE THREAD

**Issue by twerthi** [OctopusDeploy/JiraIntegration#71]
When viewing Work Item information in Jira, it is difficult to determine which Octopus Tenants have received the updated version when using the Jira - Octopus integration.

![image](https://user-images.githubusercontent.com/5552453/150040619-4b55c3a7-0347-44fe-90a4-ad540eac17e7.png)

It looks like https://github.com/OctopusDeploy/JiraIntegration/blob/a77f9ba5a8cd2a8dab52008229a1b0105e96871d/source/Server/Deployments/JiraDeployment.cs#L161 can be updated to include the Tenant name for the DisplayName property.

**Comment by domenicsim1** [comment]
Issue has been fixed in #72.
![image](https://user-images.githubusercontent.com/87625140/150443869-e7facc80-0004-41dc-a53e-cfba69b572ef.png)
